title: ICRM
description: International Committee for Radionuclide Metrology
theme: just-the-docs
color_scheme: icrm

url: https://icrm-org.github.io/icrm-new/

nav_external_links:
  - title: ICRM on GitHub
    url: https://github.com/icrm-org/icrm-new/issues
  - title: Report an issue
    url: https://github.com/icrm-org/icrm-new/issues

aux_links:
  View ICRM on GitHub: https://github.com/icrm-org/icrm-new/

callouts:
  note:
    title: Note
    color: green


# exclude:
#   - README.md
#   - LICENCE
#   - LICENCE-just-the-docs
