title: ICRM
description: International Committee for Radionuclide Metrology
theme: just-the-docs
color_scheme: icrm
logo: "./ICRM_LOGO_600dpi.jpg" 

url: https://icrm-org.github.io/icrm-new/

nav_external_links:
  - title: Report an issue
    url: https://github.com/icrm-org/icrm-new/issues

aux_links:
  View ICRM on GitHub: https://github.com/icrm-org/icrm-new/

callouts:
  note:
    title: Note
    color: green
  coordinator:
    title: Coordinator
    color: blue
  lead:
    title: Lead
    color: grey-dk
  subgroups:
    title: Subgroups
    color: grey-dk
  
math: katex

# exclude:
#   - README.md
#   - LICENCE
#   - LICENCE-just-the-docs
