title: ICRM
description: International Committee for Radionuclide Metrology
theme: just-the-docs
color_scheme: icrm

url: https://icrm-org.github.io/icrm-new/

nav_external_links:
  - title: Newsletter
    url: http://www.lnhb.fr/conferences-publications/icrm-newsletter/

# aux_links:
#   Discussions: https://github.com/icrm-org/icrm-new/discussions

# exclude:
#   - README.md
#   - LICENCE
#   - LICENCE-just-the-docs
